# Generated by Django 3.2.9 on 2021-11-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seria', models.TextField(verbose_name='Серия')),
                ('number', models.TextField(verbose_name='Номер')),
                ('data_vipusk', models.TextField(verbose_name='Дата Выпуска')),
                ('data_okonchania', models.TextField(verbose_name='Дата окончания')),
                ('data_ispolzovania', models.TextField(verbose_name='Дата использования')),
                ('summa', models.TextField(verbose_name='Сумма')),
                ('statuscard', models.CharField(choices=[('Неактивна ❌', 'Неактивна ❌'), ('Активна ✅', 'Активна ✅'), ('Просрочена', 'Просрочена')], max_length=70, verbose_name='Статус Карты')),
            ],
            options={
                'verbose_name': 'Карта',
                'verbose_name_plural': 'Карты',
            },
        ),
        migrations.CreateModel(
            name='HistoryCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card', models.PositiveIntegerField(verbose_name='ID карты')),
                ('who_buy', models.TextField(verbose_name='Кто купил')),
                ('what_buy', models.TextField(verbose_name='Что купил')),
                ('price_tovar', models.TextField(verbose_name='Цена Товара')),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупки',
            },
        ),
    ]
